# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-11 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('BINA', 'Binance'), ('GDAX', 'GDAX')], max_length=4)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SEL', 'Sell')], max_length=3)),
                ('product', models.CharField(choices=[('ETH-USD', 'ETH/USD'), ('XLM-ETH', 'XLM/ETH')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('price_paid', models.FloatField(blank=True, default=None, null=True)),
                ('quantity', models.FloatField(blank=True, default=None, null=True)),
                ('fees_paid', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('PND', 'Pending'), ('FIL', 'Filled')], max_length=3)),
                ('trades', models.ManyToManyField(related_name='transactions', to='nc.Trade')),
            ],
        ),
    ]
