# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import functools
import nc.models
import nc.validators


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0005_auto_20180518_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12)),
                ('color', models.CharField(max_length=6)),
                ('pic', models.ImageField(blank=True, default=None, null=True, upload_to=functools.partial(nc.models.profile_file_directory_path, *(), **{b'field': 'pic'}), validators=[nc.validators.FileSizeValidator(limit_value=2621440), nc.validators.MimeTypeValidator(allowed_mimetypes=[b'image/x-cmu-raster', b'image/x-xbitmap', b'image/gif', b'image/x-portable-bitmap', b'image/jpeg', b'application/x-hdf', b'application/postscript', b'image/png', b'image/vnd.microsoft.icon', b'image/x-rgb', b'video/mpeg', b'image/x-ms-bmp', b'image/x-xpixmap', b'image/x-portable-graymap', b'image/x-portable-pixmap', b'image/tiff', b'application/pdf'])])),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets_issued', to='nc.Account')),
            ],
        ),
    ]
