# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0006_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='domain',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
