# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0013_auto_20180522_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accounts_created',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
