# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0014_profile_accounts_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='trades',
        ),
        migrations.AddField(
            model_name='profile',
            name='followers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
