# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0015_auto_20180528_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_id',
            field=models.CharField(default='XLM-native', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together=set([('issuer', 'code')]),
        ),
    ]
