# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0016_auto_20180530_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
