# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0018_auto_20180530_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='issuer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets_issued', to='nc.Account'),
        ),
    ]
