# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0019_auto_20180530_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_id',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
    ]
