# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0021_asset_issuer_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together=set([('issuer_address', 'code')]),
        ),
    ]
