# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 21:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nc', '0022_auto_20180531_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='trusted_by',
            field=models.ManyToManyField(related_name='trusted_assets', to=settings.AUTH_USER_MODEL),
        ),
    ]
