# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0023_asset_trusted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='trusted_by',
        ),
    ]
