# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0024_remove_asset_trusted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='toml',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
