# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0025_asset_toml'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='display_decimals',
            field=models.PositiveSmallIntegerField(default=4),
        ),
    ]
