# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0026_asset_display_decimals'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='conditions',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='toml_pic',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
