# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0027_auto_20180602_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='color',
        ),
    ]
