# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0028_remove_asset_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='display_decimals',
            field=models.PositiveSmallIntegerField(default=7),
        ),
    ]
