# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0032_account_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_pic_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
