# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0033_account_user_pic_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='performance_1d',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='performance_1m',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='performance_1w',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='performance_1y',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='performance_3m',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='performance_6m',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
