# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0035_portfolio_rawportfoliodata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawportfoliodata',
            old_name='value',
            new_name='usd_value',
        ),
        migrations.AddField(
            model_name='rawportfoliodata',
            name='xlm_value',
            field=models.FloatField(default=-1.0),
        ),
    ]
