# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0036_auto_20180716_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='performance_1d',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='performance_1m',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='performance_1w',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='performance_1y',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='performance_3m',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='performance_6m',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rank',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='performance_1d',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='performance_1m',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='performance_1w',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='performance_1y',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='performance_3m',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='performance_6m',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='rank',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
