# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-05 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0038_auto_20180805_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsettings',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='allow_follower_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='allow_payment_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='allow_token_issuance_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='allow_trade_email',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='EmailSettings',
        ),
    ]
