# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-07 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0040_followrequest_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_is_private',
            field=models.BooleanField(default=False),
        ),
    ]
