# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-07 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0042_remove_account_profile_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followrequest',
            name='read',
        ),
    ]
