# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-07 18:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nc', '0043_remove_followrequest_read'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followrequest',
            unique_together=set([('user', 'requester')]),
        ),
    ]
