# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-31 19:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nc', '0044_auto_20180807_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='trusters',
            field=models.ManyToManyField(related_name='assets_trusting', to=settings.AUTH_USER_MODEL),
        ),
    ]
