# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-16 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0046_auto_20180914_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='notifier_subscription_id',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='StellarNotifier subscription ID'),
        ),
    ]
