# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0051_profile_allow_trust_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='assets',
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
