# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-08 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0054_auto_20181008_1400'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FundAccountRequest',
            new_name='AccountFundRequest',
        ),
    ]
